# Generated by Django 4.2.3 on 2023-07-30 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecole', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ecoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.ecole')),
            ],
        ),
    ]
