# Generated by Django 4.2 on 2023-04-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppDirecteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDirecteur.candidat')),
                ('electionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDirecteur.election')),
                ('eleveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDirecteur.eleve')),
            ],
        ),
    ]
